name: "[CHORE] Secrets"
on:
  workflow_dispatch:
    inputs:
      repo_access_token:
        description: Set REPO_ACCESS_TOKEN value
        required: false
        type: string
      deezer_arl:
        description: Set DEEZER_ARL value
        required: false
        type: string
      qobuz_user_id:
        description: Set QOBUZ_USER_ID value
        required: false
        type: string
      qobuz_token:
        description: Set QOBUZ_TOKEN value
        required: false
        type: string
      spotify_client_id:
        description: Set SPOTIFY_CLIENT_ID value
        required: false
        type: string
      spotify_client_secret:
        description: Set SPOTIFY_CLIENT_SECRET value
        required: false
        type: string
      tidal_user_id:
        description: Set TIDAL_USER_ID value
        required: false
        type: string
      tidal_country_code:
        description: Set TIDAL_COUNTRY_CODE value
        required: false
        type: string
      tidal_access_token:
        description: Set TIDAL_ACCESS_TOKEN value
        required: false
        type: string
      tidal_refresh_token:
        description: Set TIDAL_REFRESH_TOKEN value
        required: false
        type: string
      tidal_token_expiry:
        description: Set TIDAL_TOKEN_EXPIRY value
        required: false
        type: string
      ytmusic_cookie_base64:
        description: Set YTMUSIC_COOKIE_BASE64 value
        required: false
        type: string
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify user
        id: user_id
        run: |
          if [[ ${{ github.actor_id }} == '132916305' || ${{ github.actor_id }} == '112367223' ]]; then
            echo "verified=true" >> $GITHUB_OUTPUT
          else
            echo "verified=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      user-verified: ${{ steps.user_id.outputs.verified }}
  clear_runs:
    needs: verify
    if: ${{ needs.verify.outputs.user-verified == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Set REPO_ACCESS_TOKEN values
        if: ${{ inputs.repo_access_token != "" }}
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          gh secret set -a actions -b ${{ inputs.repo_access_token }}