name: '[CHORE] Secrets'
run-name: 'Update ${{ inputs.secret_name }} value'
on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: Select secret name to update
        required: true
        type: choice
        options:
          - REPO_ACCESS_TOKEN
          - DEEZER_ARL
          - QOBUZ_USER_ID
          - QOBUZ_TOKEN
          - SPOTIFY_CLIENT_ID
          - SPOTIFY_CLIENT_SECRET
          - TIDAL_USER_ID
          - TIDAL_COUNTRY_CODE
          - TIDAL_ACCESS_TOKEN
          - TIDAL_REFRESH_TOKEN
          - TIDAL_TOKEN_EXPIRY
          - TIDAL_PLATFORM
          - TIDAL_FORMATS
          - TIDAL_CLIENT_ID
          - TIDAL_CLIENT_SECRET
          - TIDAL_VALID
          - YTMUSIC_COOKIE_BASE64
          - WIDEVINE_CDM_BASE64
      secret_value:
        description: Enter updated secret value
        required: true
        type: string
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify user
        id: user_id
        run: |
          if [[ ( ${{ github.actor_id }} == '132916305' || ${{ github.actor_id }} == '112367223' ) && ${{ github.event_name }}  == 'workflow_dispatch' ]]; then
            echo "verified=true" >> $GITHUB_OUTPUT
          else
            echo "verified=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      user-verified: ${{ steps.user_id.outputs.verified }}
  secrets:
    needs: verify
    if: ${{ needs.verify.outputs.user-verified == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    env:
      GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: List all secrets
        run: |
          gh secret list -a actions
      - name: Mask ${{ inputs.secret_name }} values
        run: |
          secret_value=$(jq -r '.inputs.secret_value' $GITHUB_EVENT_PATH)
          echo ::add-mask::$secret_value
          echo "secret_value=$secret_value" >> $GITHUB_ENV
      - name: Update ${{ inputs.secret_name }} values
        run: |
          gh secret set ${{ inputs.secret_name }} -a actions -b $secret_value
