name: Streamrip
# Supported sources: Qobuz, Deezer
on:
  workflow_dispatch:
    inputs:
      command:
        description: Choose Streamrip command
        required: true
        type: choice
        options:
          - id
          - url
          - lastfm
      track_id:
        description: Set tracks ID to download (required for 'id' command)
        required: false
        type: string
      track_url:
        # seperate URL with space to download multiple
        description: Set albums/tracks link to download (required for 'url' command)
        required: false
        type: string
      lastfm_url:
        description: Set LastFM playlist link (required for 'lastfm' command)
        required: false
        type: string
      track_quality:
        description: Select tracks quality (quality depends on the source)
        required: false
        type: choice
        options:
          # check https://github.com/nathom/streamrip/wiki/Quality-IDs for supported quality per sources
          - 4 # 24 bit, ≤ 192 kHz (Hi-Res)
          - 3 # 24 bit, ≤ 96 kHz (Hi-Fi / MQA)
          - 2 # 16 bit, 44.1 kHz (CD Quality / Lossless)
          - 1 # 320 kbps (Great)
          - 0 # 128 kbps (Good)
          - config
        default: config
      track_codec:
        description: Select tracks codec
        required: false
        type: choice
        options:
          - flac
          - alac
          - ogg
          - aac
          - mp3
          - original
        default: original

permissions:
  actions: write
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.verify.outputs.run }}
    steps:
      - uses: actions/checkout@v4
      - name: Verify manual inputs
        id: verify
        run: |
          if [[ ${{ inputs.command }} == "id" && -n "${{ inputs.track_id }}" ]] || [[ ${{ inputs.command }} == "url"  && -n "${{ inputs.track_url }}" ]] || [[ ${{ inputs.command }} == "lastfm"  && -n "${{ inputs.lastfm_url }}" ]]; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "Inputs missing to run '${{ inputs.command }}' command"
            echo "run=false" >> $GITHUB_OUTPUT
          fi
  downloads:
    runs-on: ubuntu-latest
    needs: verify
    if: needs.verify.outputs.run == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade streamrip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run command
        env:
          COMMANDS: ${{ inputs.command }}
          TRACK_ID: ${{ inputs.track_id }}
          TRACK_URL: ${{ inputs.track_url }}
          LASTFM_URL: ${{ inputs.lastfm_url }}
          QUALITY: ${{ inputs.track_quality }}
          CODEC: ${{ inputs.track_codec }}
        run: |
          python -m pip --help
      - name: Generate datetime codes
        id: dt-codes
        run: |
          echo "dtcode=$(date +%N%s | sed 's/0//g' | cut --complement -c 5-10 | cut -c 3-7)" >> $GITHUB_OUTPUT
      - name: Upload downloads as artifact
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamrip-downloads-${{ steps.dt-codes.outputs.dtcode }}
          path: music
          if-no-files-found: error
          retention-days: 7
          include-hidden-files: true
      - name: Print artifact info
        run: |
          echo "id = ${{ steps.artifact.outputs.artifact-id }}"
          echo "url = ${{ steps.artifact.outputs.artifact-url }}"
