name: TidalDL-NG
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      command:
        description: Select commands to run
        required: true
        type: choice
        options:
          - DOWNLOAD
          - LOGIN
        default: DOWNLOAD
      query:
        description: Set queries to download
        required: true
        type: string

permissions:
  actions: write
  contents: read

jobs:
  downloads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'modules/tidal-dl-ng/requirements.txt'
      - name: Install python dependencies
        run: |
          python -m pip install -r modules/tidal-dl-ng/requirements.txt
      - name: Set up FFmpeg
        id: setup_ffmpeg
        uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: release
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run command
        env:
          COMMAND: ${{ inputs.command }}
          QUERY: ${{ inputs.query }}
        shell: bash
        run: |
          tdn cfg
          python -m modules.tidal-dl-ng.run
      - name: Generate datetime codes
        id: dt_codes
        shell: bash
        run: |
          echo "dtcode=$(date +%N%s | sed 's/0//g' | cut --complement -c 5-10 | cut -c 3-7)" >> $GITHUB_OUTPUT
      - name: Upload downloads as artifact
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: tidal-dl-ng-downloads-${{ steps.dt_codes.outputs.dtcode }}
          path: music
          if-no-files-found: error
          retention-days: 7
          include-hidden-files: true
      - name: Print artifact info
        shell: bash
        run: |
          echo "[INFO] artifact-id:\n"
          echo "${{ steps.artifact.outputs.artifact-id }}"
          echo "[INFO] artifact-url:\n"
          echo "${{ steps.artifact.outputs.artifact-url }}"
